name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        name: [MSVC MINGW]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Display the path by pwsh
        run: echo ${env:PATH}
        shell: pwsh
      - name: Display github.workspace by pwsh
        run: |
          echo "github.workspace is ${{github.workspace}}."
          ls ${{github.workspace}}
        shell: pwsh
      - name: MINGW
        if: startsWith(matrix.name, 'MINGW')
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          make
          cd ${{github.workspace}}\build\bin
          ls
        shell: pwsh
      - name: MSVC
        if: startsWith(matrix.name, 'MSVC')
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          cmake --build .
          cd ${{github.workspace}}\build\bin\Debug
          ls
        shell: pwsh
