name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        name: [MINGW, MSVC, LINUX]
        os: [windows-latest, ubuntu-latset]
    steps:
      - uses: actions/checkout@v1
      - name: MINGW
        if: startsWith(matrix.name, 'MINGW')
        run: |
          echo ${env:PATH}
          echo "github.workspace is ${{github.workspace}}."
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          make
          cd ${{github.workspace}}\build\bin
          ls
        shell: pwsh
      - name: MSVC
        if: startsWith(matrix.name, 'MSVC')
        run: |
          echo ${env:PATH}
          echo "github.workspace is ${{github.workspace}}."
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          cmake --build .
          cd ${{github.workspace}}\build\bin\Debug
          ls
        shell: pwsh
      - name: LINUX
        if: startsWith(matrix.name, 'LINUX')
        run: |
          cmake -S . -B ./build && cd ./build && make
          cd ./build
          ls
      
