name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy: 
      matrix:
        config:
        - {name: "MINGW", os: "windows-latest"}
        - {name: "MSVC", os: "windows-latest"}
        - {name: "LINUX", os: "ubuntu-latest"}
    steps:
      - uses: actions/checkout@v1
      - name: MINGW
        if: startsWith(matrix.config.name, 'MINGW')
        run: |
          echo ${env:PATH}
          echo "github.workspace is ${{github.workspace}}."
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          make
          cd ${{github.workspace}}\build\bin
          ls
        shell: pwsh
      - name: MSVC
        if: startsWith(matrix.config.name, 'MSVC')
        run: |
          echo ${env:PATH}
          echo "github.workspace is ${{github.workspace}}."
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          cmake --build .
          cd ${{github.workspace}}\build\bin\Debug
          ls
        shell: pwsh
      - name: LINUX
        if: startsWith(matrix.config.name, 'LINUX')
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ls
      
