name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: Windows MSVC 2022
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Display the path by pwsh
        run: echo ${env:PATH}
        shell: pwsh
      - name: Display github.workspace by pwsh
        run: |
          echo "github.workspace is ${{github.workspace}}."
          ls ${{github.workspace}}
        shell: pwsh
      - name: CMake Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          ls
        shell: pwsh
      - name: make
        run: |
          cd ${{github.workspace}}\build 
          cmake . --build
          ls
        shell: pwsh 
      - name: print bin
        run: |
          cd ${{github.workspace}}\build\bin\Debug
          ls
        shell: pwsh  
