name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy: 
      matrix:
        config:
        - {name: "MINGW", os: "windows-latest", command: "-G", compiler: "MinGW Makefiles", makecommand: "make"}
        - {name: "MSVC", os: "windows-latest", command: "-G", compiler: "Visual Studio 17 2022", makecommand: "cmake --build ."}
        - {name: "LINUX", os: "ubuntu-latest", command: "", compiler: "", makecommand: "make"}
    steps:
      - uses: actions/checkout@v2
      - name: CMAKE & PRINT
        run: |
          mkdir -p ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. ${matrix.command} "${matrix.compiler}"
          ${matrix.makecommand}
          ls
      - name: MINGW
        if: startsWith(matrix.config.name, 'MINGW')
        run: |
          sh ${{github.workspace}}/build/mingw.sh
      - name: MSVC
        if: startsWith(matrix.config.name, 'MSVC')
        run: |
          cmd.exe /C ${{github.workspace}}/build/msvc.bat
      - name: LINUX
        if: startsWith(matrix.config.name, 'LINUX')
        run: |
          sh ${{github.workspace}}/build/linux.sh
