name: Generate and Push File

on:
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate File
        run: |
          echo "| module | compiler | old version | new version | cmake result | build.log |" > result.md
          echo "| module | compiler | old version | new version | cmake result | build.log |" >> result.md
          echo "| module | compiler | old version | new version | cmake result | build.log |" >> result.md

      - name: Commit Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "HertzL1u"
          git config --global user.email "Z18873045628@163.com"
          git add result.md
          git commit -m "Generated file"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          token: ${{ env.PAT_TOKEN }}
          branch: ${{ github.ref }}
          force: true









