name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy: 
      matrix:
        config:
        - {name: "MINGW", os: "windows-latest", command: "-G", generator: "MinGW Makefiles"}
        - {name: "MSVC", os: "windows-latest", command: "-G", generator: "Visual Studio 17 2022"}
        - {name: "LINUX", os: "ubuntu-latest", command: "", generator: ""}
    steps:
      - uses: actions/checkout@v1
      - name: CMAKE & PRINT
        run: |
          mkdir build
          cd build
          cmake .. ${{matrix.command}} "${{matrix.generator}}"
          make
          ls
      - name: MINGW
        if: startsWith(matrix.config.name, 'MINGW')
        run: |
          ${{github.action_path}}
        shell: pwsh
      - name: MSVC
        if: startsWith(matrix.config.name, 'MSVC')
        run: |
          ${{github.action_path}}
        shell: pwsh
      - name: LINUX
        if: startsWith(matrix.config.name, 'LINUX')
        run: |
          ${{github.action_path}}
