name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: MYJOB
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMAKE & PRINT
        run: |
          git clone https://github.com/HertzL1u/cmake5.git
          git config --global user.email "Z18873045628@163.com"
          git config --global user.name "HertzL1u"
          git add my_folder
          git commit -m "Add my_folder"
          git push
        shell: pwsh
