name: Cmake-dll
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs :
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy: 
      matrix:
        config:
        - {name: "MINGW", os: "windows-latest", command: "-G", compiler: "MinGW Makefiles", makecommand: "make"}
        - {name: "MSVC", os: "windows-latest", command: "-G", compiler: "Visual Studio 17 2022", makecommand: "cmake --build ."}
        - {name: "LINUX", os: "ubuntu-latest", command: "", compiler: "", makecommand: "make"}
    steps:
      - uses: actions/checkout@v2
      - name: CMAKE & PRINT
        run: |
          mkdir build
          cd build
          cmake .. ${matrix.command} "\"${matrix.compiler}\""
          ${matrix.makecommand}
          ls
        shell: pwsh
      - name: MINGW
        if: startsWith(matrix.config.name, 'MINGW')
        run: |
          ${{github.action_path}}
        shell: bash
      - name: MSVC
        if: startsWith(matrix.config.name, 'MSVC')
        run: |
          ${{github.action_path}}
        shell: bash
      - name: LINUX
        if: startsWith(matrix.config.name, 'LINUX')
        run: |
          ${{github.action_path}}
